services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - ibira-network
  
  postgresql:
    container_name: resource-cataloguer-db
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_USER: 'ibira-cataloger'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'catalog'
    volumes:
      - ./models/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
      
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ibira-network

  ibirapitanga-data-collector:
    container_name: data-collector
    image: test-collector-datacollector
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - ibira-network

  ibirapitanga-resource-adaptor:
    image: ghcr.io/iptsp/ibirapitanga-resource-adaptor:latest
    container_name: resource-adater
    ports:
      - "8084:8080"
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - app-network

  ibirapitanga-resource-cataloger:
    image: ghcr.io/iptsp/ibirapitanga-resource-cataloger:latest
    container_name: resource-cataloger
    build: .
    restart: always
    depends_on:
      - 'postgresql'
    environment:
      DATABASE_URL: postgresql://ibira-cataloger:admin@resource-cataloguer-db:5432/catalog
      POSTGRES_USER: 'cataloger'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_HOST: 'resource-cataloguer-db'
      POSTGRES_PORT: 5432
      RABBITMQ_HOST: 'rabbitmq'
      KONG_URI: 'http://kong:8001'
    ports:
      - 8080:8080

networks:
  ibira-network:
    driver: bridge
volumes:
  mongo-data:
